name: Run module tests

on:
  pull_request:
    paths-ignore:
      - '**.md'

  schedule:
    - cron:  '0 6 * * *'

env:
   DRUPAL_TESTING_TEST_CODING_STYLES: false
   DRUPAL_TESTING_DATABASE_USER: root
   DRUPAL_TESTING_DATABASE_PASSWORD: root
   DRUPAL_TESTING_DATABASE_ENGINE: mysql
   DRUPAL_TESTING_DRUPAL_VERSION: '~8.8.0'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        PHP: ['7.3', '7.4']

    steps:
    - uses: actions/checkout@v1

    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.PHP }}

    - name: Start MySql service
      run: sudo /etc/init.d/mysql start

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Get build environment
      run: composer global require thunder/drupal-testing

    - name: Run the tests
      run: test-drupal-project
