name: Run module tests

on:
  pull_request:
    paths-ignore:
      - '**.md'

  schedule:
    - cron:  '0 6 * * *'

env:
  DRUPAL_TESTING_TEST_CODING_STYLES: false
  DRUPAL_TESTING_DATABASE_USER: root
  DRUPAL_TESTING_DATABASE_PASSWORD: root
  DRUPAL_TESTING_DATABASE_ENGINE: mysql
  DRUPAL_TESTING_HTTP_PORT: 8888

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    strategy:
      matrix:
        PHP_VERSION: [ '7.4', '8.0' ]

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.PHP_VERSION }}
        extensions: Imagick, gd, pdo_mysql

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Get build environment
      run: composer global require thunder/drupal-testing

    - name: Setup Apache
      uses: thunder/apache-shiva-php-action@v1
      with:
        php-version: ${{ matrix.PHP_VERSION }}
        site-directory: /tmp/test/select2/install/web
        http-port: ${{ env.DRUPAL_TESTING_HTTP_PORT }}

    - name: Run the tests
      run: test-drupal-project
